#!/usr/bin/env bash
# gowork.sh — the go.work an EDITOR needs at this repository's root.
#
# THE PROBLEM. A unit is its own Go module and deliberately does not `require`
# core: it imports github.com/margince/margince/backend/pkg/extension, and that
# import is resolved by the COMPOSED workspace gen-composition writes under
# core/build/composition/. Every lane here passes that file as GOWORK, so builds
# and tests are fine. An editor is not: gopls opens extensions/<unit>/ , finds no
# workspace above it, loads the module on its own, and reports
#
#   could not import github.com/margince/margince/backend/pkg/extension
#   (no required module provides package …)
#
# on the unit's very first import line. The code is correct and the build is
# green, which makes it the worst kind of red squiggle.
#
# THE FIX. A workspace at this root that `use`s core's backend and each unit
# here. It resolves the surface the same way the composed one does, and it names
# the SOURCES — so the editor sends you to extensions/<unit>/…, never to the
# staged copy under core/.
#
# GENERATED, not tracked: the member list is the unit set, which changes when
# anyone adds a unit. `stage` refreshes it, so it cannot go stale in normal use.
# Our lanes are unaffected either way — every one of them passes GOWORK
# explicitly, and a command run inside core/ finds core's own go.work first.
set -euo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

[ -f "$CORE/go.work" ] || exit 0   # no submodule yet; init runs this again

# The go directive must match core's: the workspace's version has to be at least
# every member's, and core's backend is the highest here.
go_version="$(awk '/^go /{print $2; exit}' "$CORE/go.work")"

# lib.sh's CORE is ABSOLUTE; a workspace member must be relative to this file.
core_rel="${CORE#"$ROOT"/}"

target="$ROOT/go.work"
tmp="$(mktemp)"
{
  cat <<EOF
// GENERATED by scripts/gowork.sh (\`make config\`, and every \`make stage\`).
// Do not edit; do not commit — it is gitignored.
//
// This file exists FOR EDITORS. A unit resolves the core surface through the
// composed workspace under core/build/composition/, which every lane passes as
// GOWORK — but gopls has no way to know that, so without this it reports every
// unit's first import as unresolvable. Members are the SOURCES here, never the
// staged copies under core/, so the editor sends you to the file you may edit.

go $go_version

use (
	./$core_rel/backend
EOF
  while IFS= read -r unit; do
    [ -n "$unit" ] || continue
    [ -f "$SRC_EXT/$unit/go.mod" ] || continue
    printf '\t./extensions/%s\n' "$unit"
  done <<EOF
$(source_units)
EOF
  printf ')\n'
} > "$tmp"

# Written only when it would change, so `make stage` — which runs on nearly
# every lane — does not touch the mtime and make the editor reload for nothing.
if [ ! -f "$target" ] || ! cmp -s "$tmp" "$target"; then
  mv "$tmp" "$target"
  echo "gowork: refreshed go.work ($(grep -c '^\t\./extensions/' "$target") unit(s) + core/backend)"
else
  rm -f "$tmp"
fi
