#!/usr/bin/env bash
# tsconfig-editor.sh — the tsconfig an EDITOR needs for a unit's frontend.
#
# The TypeScript twin of scripts/gowork.sh. A unit's screen imports the host
# surface by name:
#
#   import { api } from "@margince/frontend/api";
#
# At build time that resolves through vite.config.ts's aliases and
# core/frontend/tsconfig.composed.json. An editor sees neither: there is no
# tsconfig above extensions/<unit>/frontend/screen.tsx, so tsserver infers a
# project and reports every import in the file as unresolvable —
#
#   Cannot find module '@margince/frontend/api' or its corresponding type
#   declarations. ts(2307)
#
# — react and @tanstack/react-query included, because a unit's frontend/ stopped
# being a member of the root pnpm workspace: its dependencies are installed by the
# COMPOSED workspace, which an editor knows nothing about either.
#
# This writes one tsconfig at this root. tsserver finds it walking up from the
# file and gets the same map the composed lane uses.
#
# WHY IT EXTENDS CORE'S COMPOSED CONFIG rather than restating the options: a
# unit's imports pull core's own src into the program (the surface is source, not
# a .d.ts), so that source is checked here too — and it must be checked with the
# options core checks it under. Restating them meant 65 errors from core's own
# design system; extending them means zero.
#
# GENERATED, not tracked: every path points into core/, whose layout is
# upstream's to change. `make stage` refreshes it. It is deliberately NOT a
# per-unit file — a tsconfig inside extensions/<unit>/ would be staged into
# core/ with the unit and change its digest.
set -euo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

[ -f "$CORE/frontend/tsconfig.composed.json" ] || exit 0   # no submodule yet
core_rel="${CORE#"$ROOT"/}"

# vite/client's ambient types (import.meta.env, ?raw imports) are needed by nine
# files in core's src. `types: ["vite/client"]` cannot resolve from this root —
# there is no node_modules here — so it is referenced by relative PATH instead,
# which can.
mkdir -p "$ROOT/.tsc"
printf '/// <reference path="../%s/frontend/node_modules/vite/client.d.ts" />\n' "$core_rel" \
  > "$ROOT/.tsc/ambient.d.ts"

target="$ROOT/tsconfig.json"
tmp="$(mktemp)"
cat > "$tmp" <<JSON
{
  "//": [
    "GENERATED by scripts/tsconfig-editor.sh (\`make config\`, and every \`make stage\`).",
    "Do not edit; do not commit — it is gitignored.",
    "",
    "This file exists FOR EDITORS. It extends core's composed config, so a unit",
    "is checked exactly as the composed lane checks it, and restates the path map",
    "root-relative because paths in an extending config REPLACE the base's rather",
    "than merging with them."
  ],
  "extends": "./$core_rel/frontend/tsconfig.composed.json",
  "compilerOptions": {
    "baseUrl": ".",
    "types": [],
    "paths": {
      "@margince/frontend/design-system": ["$core_rel/frontend/src/surface/design-system.ts"],
      "@margince/frontend/api": ["$core_rel/frontend/src/surface/api.ts"],
      "@margince/frontend/app": ["$core_rel/frontend/src/surface/index.ts"],

      "@margince-ext/*": ["extensions/*/frontend", "$core_rel/extensions/*/frontend"],

      "@composition/extensions": ["$core_rel/build/composition/frontend/extensions.gen"],
      "@composition/screens": ["$core_rel/build/composition/frontend/extscreens.gen"],
      "@composition/copy": ["$core_rel/build/composition/frontend/extlocales.gen"],
      "@composition/schema": ["$core_rel/build/composition-frontend/schema"],

      "react": ["$core_rel/frontend/node_modules/@types/react", "$core_rel/frontend/node_modules/react"],
      "react/*": ["$core_rel/frontend/node_modules/@types/react/*", "$core_rel/frontend/node_modules/react/*"],
      "react-dom": ["$core_rel/frontend/node_modules/@types/react-dom", "$core_rel/frontend/node_modules/react-dom"],
      "react-dom/*": ["$core_rel/frontend/node_modules/@types/react-dom/*", "$core_rel/frontend/node_modules/react-dom/*"],
      "@tanstack/react-query": ["$core_rel/frontend/node_modules/@tanstack/react-query"],
      "vitest": ["$core_rel/frontend/node_modules/vitest"],
      "@testing-library/react": ["$core_rel/frontend/node_modules/@testing-library/react"],
      "@testing-library/user-event": ["$core_rel/frontend/node_modules/@testing-library/user-event"]
    }
  },
  "files": [".tsc/ambient.d.ts"],
  "include": [
    "$core_rel/frontend/src",
    "extensions/*/frontend/**/*.ts",
    "extensions/*/frontend/**/*.tsx"
  ],
  "exclude": ["$core_rel/frontend/src/**/*.test.ts", "$core_rel/frontend/src/**/*.test.tsx"]
}
JSON

if [ ! -f "$target" ] || ! cmp -s "$tmp" "$target"; then
  mv "$tmp" "$target"
  echo "tsconfig: refreshed tsconfig.json (editor support for extensions/*/frontend)"
else
  rm -f "$tmp"
fi
